const airports = [
  { value: "ATL", label: "Atlanta, USA" },
  { value: "LAX", label: "Los Angeles, USA" },
  { value: "JFK", label: "New York - JFK, USA" },
  { value: "ORD", label: "Chicago O'Hare, USA" },
  { value: "CDG", label: "Paris Charles de Gaulle, France" },
  { value: "LHR", label: "London Heathrow, UK" },
  { value: "AMS", label: "Amsterdam Schiphol, Netherlands" },
  { value: "FRA", label: "Frankfurt, Germany" },
  { value: "MAD", label: "Madrid Barajas, Spain" },
  { value: "BCN", label: "Barcelona El Prat, Spain" },
  { value: "MUC", label: "Munich, Germany" },
  { value: "FCO", label: "Rome Fiumicino, Italy" },
  { value: "MXP", label: "Milan Malpensa, Italy" },
  { value: "ZRH", label: "Zurich, Switzerland" },
  { value: "BRU", label: "Brussels, Belgium" },
  { value: "VIE", label: "Vienna, Austria" },
  { value: "CPT", label: "Cape Town, South Africa" },
  { value: "JNB", label: "Johannesburg, South Africa" },
  { value: "DXB", label: "Dubai, UAE" },
  { value: "DOH", label: "Doha, Qatar" },
  { value: "IST", label: "Istanbul, Turkey" },
  { value: "HND", label: "Tokyo Haneda, Japan" },
  { value: "NRT", label: "Tokyo Narita, Japan" },
  { value: "ICN", label: "Seoul Incheon, South Korea" },
  { value: "PEK", label: "Beijing Capital, China" },
  { value: "PVG", label: "Shanghai Pudong, China" },
  { value: "HKG", label: "Hong Kong, China" },
  { value: "SYD", label: "Sydney, Australia" },
  { value: "MEL", label: "Melbourne, Australia" },
  { value: "AKL", label: "Auckland, New Zealand" },
  { value: "GRU", label: "São Paulo Guarulhos, Brazil" },
  { value: "GIG", label: "Rio de Janeiro Galeão, Brazil" },
  { value: "EZE", label: "Buenos Aires Ezeiza, Argentina" },
  { value: "SCL", label: "Santiago, Chile" },
  { value: "BOG", label: "Bogotá El Dorado, Colombia" },
  { value: "LIM", label: "Lima Jorge Chávez, Peru" },
  { value: "MEX", label: "Mexico City, Mexico" },
  { value: "CUN", label: "Cancún, Mexico" },
  { value: "YYZ", label: "Toronto Pearson, Canada" },
  { value: "YVR", label: "Vancouver, Canada" },
  { value: "YUL", label: "Montreal Trudeau, Canada" },
  { value: "BKK", label: "Bangkok Suvarnabhumi, Thailand" },
  { value: "SIN", label: "Singapore Changi, Singapore" },
  { value: "KUL", label: "Kuala Lumpur, Malaysia" },
  { value: "CGK", label: "Jakarta Soekarno-Hatta, Indonesia" },
  { value: "DEL", label: "Delhi Indira Gandhi, India" },
  { value: "BOM", label: "Mumbai Chhatrapati Shivaji, India" },
  { value: "JED", label: "Jeddah King Abdulaziz, Saudi Arabia" },
  { value: "RUH", label: "Riyadh King Khalid, Saudi Arabia" },
  { value: "TLV", label: "Tel Aviv Ben Gurion, Israel" },
];

export default airports;
